name: Cloud Service CD Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy the team-onboarding to'
        required: true
        type: choice
        options:
          - inf
          - dev
          - qa
          - prod
      target_deploy:
        description: 'Target deploy to specific Environment for Hotfix'
        required: true
        type: boolean

jobs:
  CD:
    uses: TanishGuleria/new-relic-reusable-flow/.github/workflows/CD-reusable.yaml@main
    secrets:
      # Could be imporoved by using a common secrect vault eg : hashicopvault
      # for now using repo secrect 
      # Add secrects to repo secrect for different environments eg : - 
      #inf_AWS_ACCESS_KEY_ID, inf_AWS_SECRET_ACCESS_KEY
      inf_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      inf_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      dev_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      dev_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      qa_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      qa_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      prod_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      prod_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PAT_TOKEN: ${{ secrets.TOKEN }}
    with:
      branch: ${GITHUB_REF#refs/heads/}
      environment: ${{ inputs.environment }}
      target_deploy: ${{ inputs.target_deploy }}
  