name: Cloud Service CD Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy the team-onboarding to'
        required: true
        type: choice
        options:
          - inf
          - dev
          - qa
          - prod
      branch:
        description: 'Branch to deploy the Service Terraform code from'
        required: true
        default: 'main'
        type: string
      target_deploy:
        description: 'Target deploy to specific Environment for Hotfix'
        required: true
        type: boolean

jobs:
  CD:
    uses: TanishGuleria/new-relic-reusable-flow/.github/workflows/CD-reusable.yaml@main
    secrets:
      PAT_TOKEN: ${{ secrets.TOKEN }}
    with:
      branch: ${{ inputs.branch }}
      environment: ${{ inputs.environment }}
      target_deploy: ${{ inputs.target_deploy }}
  