name: Cloud Service CI Workflow
on:
  workflow_dispatch:
  push:
    branch:
      - main
      - develop
      - feature/*
  
jobs:
  CI:
    run-on: ubuntu-latest
    uses: TanishGuleria/new-relic-reusable-flow/.github/workflows/CI-reusable.yaml@main 
    secrects:
      PAT_TOKEN: ${{ secrets.TOKEN }}
    with:
      dummy_input: "dummy-input-value"



  