name: Cloud Service CI Workflow
on:
  workflow_dispatch:
  push:
    branch:
      - main
      - develop
      - feature/*
  
jobs:
  CI:
    uses: TanishGuleria/new-relic-reusable-flow/.github/workflows/CI-reusable.yaml@main 
    secrets:
      PAT_TOKEN: ${{ secrets.TOKEN }}
    with:
      container_port: 5000
      app_name: "new-relic-cloud-app"
  
  Trigger-CD:
    needs: CI
    runs-on: ubuntu-latest 
    steps:
      - name: Trigger CD 
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const branchName = context.ref.replace('refs/heads/', '');
            
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo, 
              workflow_id: 'CD.yaml', 
              ref: branchName,  // Use the extracted branch name
              inputs: {
                environment: 'inf',
                targeted_deploy: 'false',
              }
            });
